'use client';

import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'de' | 'vi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Header
    'nav.home': 'Home',
    'nav.menu': 'Menu',
    'nav.booking': 'Booking',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    
    // Hero
    'hero.title': 'Chang Restaurant',
    'hero.subtitle': 'Experience the authentic flavors of Asia in an elegant atmosphere. Fresh ingredients, traditional recipes, and exceptional service.',
    'hero.reserve': 'Reserve Table',
    'hero.menu': 'View Menu',
    
    // Menu
    'menu.title': 'Our Menu',
    'menu.subtitle': 'Discover our carefully crafted dishes made with the finest ingredients',
    'menu.recommendations': 'Our Recommendations',
    'menu.ourRecommendations': 'UNSERE KÜCHE EMPFIEHLT',
    'menu.appetizers': 'Appetizers',
    'menu.salads': 'Salads',
    'menu.mains': 'Main Courses',
    'menu.desserts': 'Desserts',
    'menu.beverages': 'Beverages',
    'menu.addToOrder': 'Add to Order',
    'menu.spicy': 'Spicy',
    'menu.vegetarian': 'Vegetarian',
    'menu.featured': 'Featured',
    
    // Booking
    'booking.title': 'Table Reservation at Chang Bistro Restaurant',
    'booking.poweredBy': 'POWERED BY RESERV.ON',
    'booking.description': 'Refined Thai cuisine and international specialties – modern interpretation, seasonally coordinated and festively presented. Whether alone for a relaxed feel-good dinner or with friends and family for a feast for the senses – you are warmly welcome with us. We look forward to your visit and to preparing an unforgettable evening for you.',
    'booking.date': 'Date',
    'booking.guests': 'Number of Guests',
    'booking.times': 'Available Times',
    'booking.selectDate': 'Please select a date first',
    'booking.moreThan10': 'More than 10 people?',
    'booking.email': 'E-Mail',
    'booking.call': 'Call',
    'booking.continue': 'CONTINUE',
    'booking.contactInfo': 'Contact Information',
    'booking.firstName': 'First Name',
    'booking.lastName': 'Last Name',
    'booking.emailAddress': 'Email Address',
    'booking.phone': 'Phone Number',
    'booking.specialRequests': 'Special Requests',
    'booking.specialRequestsPlaceholder': 'Allergies, dietary restrictions, special occasions...',
    'booking.confirmReservation': 'CONFIRM RESERVATION',
    'booking.back': 'BACK',
    'booking.reservationSuccess': 'Reservation confirmed for {guests} people on {date} at {time}.\n\nWe look forward to welcoming you!',
    
    // About
    'about.title': 'About Chang Restaurant',
    'about.subtitle': 'A culinary journey through Asia with authentic flavors and modern presentation',
    'about.story': 'Our Story',
    'about.storyText1': 'Founded in 2015, Chang Restaurant has been dedicated to bringing authentic Asian cuisine to the heart of the city. Our master chefs combine traditional cooking techniques with fresh, locally-sourced ingredients to create unforgettable dining experiences.',
    'about.storyText2': 'We believe that food is more than nourishment – it\'s a way to bring people together, share cultures, and create lasting memories. Every dish tells a story of heritage, passion, and craftsmanship.',
    'about.awardWinning': 'Award Winning',
    'about.awardText': 'Recognized by local food critics and honored with multiple culinary awards',
    'about.madeWithLove': 'Made with Love',
    'about.loveText': 'Every dish is prepared with passion and attention to detail by our skilled chefs',
    'about.freshIngredients': 'Fresh Ingredients',
    'about.freshText': 'We source the finest ingredients daily to ensure quality and authenticity',
    
    // Contact
    'contact.title': 'Visit Us',
    'contact.subtitle': 'Find us in the heart of the city, ready to serve you exceptional cuisine',
    'contact.address': 'Address',
    'contact.phone': 'Phone',
    'contact.email': 'Email',
    'contact.hours': 'Hours',
    'contact.findUs': 'Find Us',
    'contact.mapComing': 'Interactive map coming soon',
    
    // Cart
    'cart.title': 'Your Order',
    'cart.empty': 'Your cart is empty',
    'cart.emptySubtext': 'Add some delicious items from our menu',
    'cart.contactInfo': 'Contact Information',
    'cart.addContactInfo': 'Add contact information',
    'cart.deliveryMethod': 'Delivery Method',
    'cart.selectDeliveryMethod': 'Select delivery method',
    'cart.orderItems': 'Order Items',
    'cart.subtotal': 'Subtotal',
    'cart.tax': 'Tax',
    'cart.total': 'Total:',
    'cart.continue': 'Continue',
    'cart.back': 'Back',
    'cart.fullName': 'Full Name',
    'cart.enterName': 'Enter your full name',
    'cart.phone': 'Phone Number',
    'cart.email': 'Email Address',
    'cart.pickup': 'Pickup',
    'cart.delivery': 'Delivery',
    'cart.pickupTime': '15-25 minutes',
    'cart.deliveryTime': '30-45 minutes',
    'cart.deliveryAddress': 'Delivery Address',
    'cart.enterAddress': 'Enter your delivery address',
    'cart.paymentMethod': 'Payment Method',
    'cart.cash': 'Cash',
    'cart.card': 'Card',
    'cart.payOnDelivery': 'Pay on delivery/pickup',
    'cart.payOnline': 'Pay online',
    'cart.specialNotes': 'Special Notes',
    'cart.notesPlaceholder': 'Allergies, special requests...',
    'cart.orderSummary': 'Order Summary',
    'cart.deliveryInfo': 'Delivery Information',
    'cart.contact': 'Contact',
    'cart.method': 'Method',
    'cart.address': 'Address',
    'cart.payment': 'Payment',
    'cart.placeOrder': 'Place Order',
    'cart.termsNote': 'By placing this order you accept our terms and conditions',
    'cart.orderSuccess': 'Order placed successfully!\n\nItems: {items}\nTotal: €{total}\nContact: {contact}\nMethod: {method}\n\nThank you for your order!',
    
    // Footer
    'footer.description': 'Experience authentic Asian cuisine in an elegant atmosphere. Fresh ingredients, traditional recipes, and exceptional service.',
    'footer.quickLinks': 'Quick Links',
    'footer.contact': 'Contact',
    'footer.rights': '© 2025 Chang Restaurant. All rights reserved.',
    
    // Admin
    'admin.dashboard': 'Dashboard',
    'admin.overview': 'Overview',
    'admin.reservations': 'Reservations',
    'admin.orders': 'Orders',
    'admin.menuManagement': 'Menu Management',
    'admin.backToWebsite': 'Back to Website',
    'admin.selectTimeSlot': 'Select Time Slot',
    'admin.tableOverview': 'Table Overview',
    'admin.table': 'Table',
    'admin.seats': 'seats',
    'admin.at': 'at',
    'admin.people': 'people',
    'admin.manageReservations': 'Manage Reservations',
    'admin.manageOrders': 'Manage Orders',
    'admin.specialRequests': 'Special Requests',
    'admin.approve': 'Approve',
    'admin.reject': 'Reject',
    'admin.edit': 'Edit',
    'admin.orderedItems': 'Ordered Items',
    'admin.deliveryAddress': 'Delivery Address',
    'admin.delivery': 'Delivery',
    'admin.pickup': 'Pickup',
    'admin.addNewDish': 'Add New Dish',
    'admin.available': 'Available',
    'admin.unavailable': 'Unavailable',
    'admin.tableManagement': 'Table Management',
    'admin.addNewTable': 'Add New Table',
    'admin.editTable': 'Edit Table',
    'admin.addTable': 'Add Table',
    'admin.updateTable': 'Update Table',
    'admin.numberOfSeats': 'Number of Seats',
    'admin.location': 'Location',
    'admin.enterLocation': 'Enter table location',
    'admin.active': 'Active',
    'admin.maintenance': 'Maintenance',
    'admin.activeDesc': 'Table can be used',
    'admin.maintenanceDesc': 'Table under maintenance',
    'admin.dishName': 'Dish Name',
    'admin.description': 'Description',
    'admin.price': 'Price',
    'admin.category': 'Category',
    'admin.addDish': 'Add Dish',
    'admin.status.available': 'Available',
    'admin.status.occupied': 'Occupied',
    'admin.status.reserved': 'Reserved',
    'admin.status.cleaning': 'Cleaning',
    'admin.reservationStatus.pending': 'Pending',
    'admin.reservationStatus.confirmed': 'Confirmed',
    'admin.reservationStatus.rejected': 'Rejected',
    'admin.orderStatus.pending': 'Pending',
    'admin.orderStatus.confirmed': 'Confirmed',
    'admin.orderStatus.rejected': 'Rejected',
  },
  de: {
    // Header
    'nav.home': 'Startseite',
    'nav.menu': 'Speisekarte',
    'nav.booking': 'Reservierung',
    'nav.about': 'Über uns',
    'nav.contact': 'Kontakt',
    
    // Hero
    'hero.title': 'Chang Restaurant',
    'hero.subtitle': 'Erleben Sie die authentischen Aromen Asiens in eleganter Atmosphäre. Frische Zutaten, traditionelle Rezepte und außergewöhnlicher Service.',
    'hero.reserve': 'Tisch reservieren',
    'hero.menu': 'Speisekarte ansehen',
    
    // Menu
    'menu.title': 'Unsere Speisekarte',
    'menu.subtitle': 'Entdecken Sie unsere sorgfältig zubereiteten Gerichte aus den besten Zutaten',
    'menu.recommendations': 'Unsere Empfehlungen',
    'menu.ourRecommendations': 'UNSERE KÜCHE EMPFIEHLT',
    'menu.appetizers': 'Vorspeisen',
    'menu.salads': 'Salate',
    'menu.mains': 'Hauptgerichte',
    'menu.desserts': 'Desserts',
    'menu.beverages': 'Getränke',
    'menu.addToOrder': 'Zur Bestellung hinzufügen',
    'menu.spicy': 'Scharf',
    'menu.vegetarian': 'Vegetarisch',
    'menu.featured': 'Empfohlen',
    
    // Booking
    'booking.title': 'Tischreservierung im Restaurant Chang Bistro',
    'booking.poweredBy': 'POWERED BY RESERV.ON',
    'booking.description': 'raffinierte Thai-Küche und internationale Spezialitäten – modern interpretiert, saisonal abgestimmt und festlich präsentiert. Ob alleine für ein entspanntes Wohlfühl-Dinner oder mit Freunden und Familie für ein Fest der Sinne – bei uns sind Sie herzlich willkommen. Wir freuen uns auf Ihren Besuch und darauf, Ihnen einen unvergesslichen Abend zu bereiten.',
    'booking.date': 'Datum',
    'booking.guests': 'Personenzahl',
    'booking.times': 'Verfügbare Uhrzeiten',
    'booking.selectDate': 'Bitte wählen Sie zuerst ein Datum',
    'booking.moreThan10': 'Mehr als 10 Personen?',
    'booking.email': 'E-Mail',
    'booking.call': 'Anruf',
    'booking.continue': 'WEITER',
    'booking.contactInfo': 'Kontaktinformationen',
    'booking.firstName': 'Vorname',
    'booking.lastName': 'Nachname',
    'booking.emailAddress': 'E-Mail-Adresse',
    'booking.phone': 'Telefonnummer',
    'booking.specialRequests': 'Besondere Wünsche',
    'booking.specialRequestsPlaceholder': 'Allergien, Ernährungseinschränkungen, besondere Anlässe...',
    'booking.confirmReservation': 'RESERVIERUNG BESTÄTIGEN',
    'booking.back': 'ZURÜCK',
    'booking.reservationSuccess': 'Reservierung bestätigt für {guests} Personen am {date} um {time} Uhr.\n\nWir freuen uns darauf, Sie zu begrüßen!',
    
    // About
    'about.title': 'Über Chang Restaurant',
    'about.subtitle': 'Eine kulinarische Reise durch Asien mit authentischen Aromen und moderner Präsentation',
    'about.story': 'Unsere Geschichte',
    'about.storyText1': 'Das Chang Restaurant wurde 2015 gegründet und widmet sich seitdem der authentischen asiatischen Küche im Herzen der Stadt. Unsere Meisterköche kombinieren traditionelle Kochtechniken mit frischen, lokal bezogenen Zutaten.',
    'about.storyText2': 'Wir glauben, dass Essen mehr als Nahrung ist – es ist ein Weg, Menschen zusammenzubringen, Kulturen zu teilen und bleibende Erinnerungen zu schaffen.',
    'about.awardWinning': 'Preisgekrönt',
    'about.awardText': 'Anerkannt von lokalen Foodkritikern und mit mehreren kulinarischen Auszeichnungen geehrt',
    'about.madeWithLove': 'Mit Liebe gemacht',
    'about.loveText': 'Jedes Gericht wird mit Leidenschaft und Liebe zum Detail von unseren erfahrenen Köchen zubereitet',
    'about.freshIngredients': 'Frische Zutaten',
    'about.freshText': 'Wir beziehen täglich die besten Zutaten, um Qualität und Authentizität zu gewährleisten',
    
    // Contact
    'contact.title': 'Besuchen Sie uns',
    'contact.subtitle': 'Finden Sie uns im Herzen der Stadt, bereit, Ihnen außergewöhnliche Küche zu servieren',
    'contact.address': 'Adresse',
    'contact.phone': 'Telefon',
    'contact.email': 'E-Mail',
    'contact.hours': 'Öffnungszeiten',
    'contact.findUs': 'Finden Sie uns',
    'contact.mapComing': 'Interaktive Karte kommt bald',
    
    // Cart
    'cart.title': 'Ihre Bestellung',
    'cart.empty': 'Ihr Warenkorb ist leer',
    'cart.emptySubtext': 'Fügen Sie köstliche Gerichte aus unserer Speisekarte hinzu',
    'cart.contactInfo': 'Kontaktinformationen',
    'cart.addContactInfo': 'Kontaktinformationen hinzufügen',
    'cart.deliveryMethod': 'Liefermethode',
    'cart.selectDeliveryMethod': 'Liefermethode wählen',
    'cart.orderItems': 'Bestellte Artikel',
    'cart.subtotal': 'Zwischensumme',
    'cart.tax': 'MwSt',
    'cart.total': 'Gesamt:',
    'cart.continue': 'Weiter',
    'cart.back': 'Zurück',
    'cart.fullName': 'Vollständiger Name',
    'cart.enterName': 'Geben Sie Ihren vollständigen Namen ein',
    'cart.phone': 'Telefonnummer',
    'cart.email': 'E-Mail-Adresse',
    'cart.pickup': 'Abholung',
    'cart.delivery': 'Lieferung',
    'cart.pickupTime': '15-25 Minuten',
    'cart.deliveryTime': '30-45 Minuten',
    'cart.deliveryAddress': 'Lieferadresse',
    'cart.enterAddress': 'Geben Sie Ihre Lieferadresse ein',
    'cart.paymentMethod': 'Zahlungsmethode',
    'cart.cash': 'Bar',
    'cart.card': 'Karte',
    'cart.payOnDelivery': 'Bei Lieferung/Abholung bezahlen',
    'cart.payOnline': 'Online bezahlen',
    'cart.specialNotes': 'Besondere Hinweise',
    'cart.notesPlaceholder': 'Allergien, besondere Wünsche...',
    'cart.orderSummary': 'Bestellübersicht',
    'cart.deliveryInfo': 'Lieferinformationen',
    'cart.contact': 'Kontakt',
    'cart.method': 'Methode',
    'cart.address': 'Adresse',
    'cart.payment': 'Zahlung',
    'cart.placeOrder': 'Bestellung aufgeben',
    'cart.termsNote': 'Mit der Bestellung akzeptieren Sie unsere Geschäftsbedingungen',
    'cart.orderSuccess': 'Bestellung erfolgreich aufgegeben!\n\nArtikel: {items}\nGesamt: €{total}\nKontakt: {contact}\nMethode: {method}\n\nVielen Dank für Ihre Bestellung!',
    
    // Footer
    'footer.description': 'Erleben Sie authentische asiatische Küche in eleganter Atmosphäre. Frische Zutaten, traditionelle Rezepte und außergewöhnlicher Service.',
    'footer.quickLinks': 'Schnelllinks',
    'footer.contact': 'Kontakt',
    'footer.rights': '© 2025 Chang Restaurant. Alle Rechte vorbehalten.',
    
    // Admin
    'admin.dashboard': 'Dashboard',
    'admin.overview': 'Übersicht',
    'admin.reservations': 'Reservierungen',
    'admin.orders': 'Bestellungen',
    'admin.menuManagement': 'Menü verwalten',
    'admin.backToWebsite': 'Zurück zur Website',
    'admin.selectTimeSlot': 'Zeitslot auswählen',
    'admin.tableOverview': 'Tischübersicht',
    'admin.table': 'Tisch',
    'admin.seats': 'Plätze',
    'admin.at': 'um',
    'admin.people': 'Personen',
    'admin.manageReservations': 'Reservierungen verwalten',
    'admin.manageOrders': 'Bestellungen verwalten',
    'admin.specialRequests': 'Besondere Wünsche',
    'admin.approve': 'Bestätigen',
    'admin.reject': 'Ablehnen',
    'admin.edit': 'Bearbeiten',
    'admin.orderedItems': 'Bestellte Artikel',
    'admin.deliveryAddress': 'Lieferadresse',
    'admin.delivery': 'Lieferung',
    'admin.pickup': 'Abholung',
    'admin.addNewDish': 'Neues Gericht hinzufügen',
    'admin.available': 'Verfügbar',
    'admin.unavailable': 'Nicht verfügbar',
    'admin.tableManagement': 'Tischverwaltung',
    'admin.addNewTable': 'Neuen Tisch hinzufügen',
    'admin.editTable': 'Tisch bearbeiten',
    'admin.addTable': 'Tisch hinzufügen',
    'admin.updateTable': 'Tisch aktualisieren',
    'admin.numberOfSeats': 'Anzahl Sitzplätze',
    'admin.location': 'Standort',
    'admin.enterLocation': 'Tischstandort eingeben',
    'admin.active': 'Aktiv',
    'admin.maintenance': 'Wartung',
    'admin.activeDesc': 'Tisch kann genutzt werden',
    'admin.maintenanceDesc': 'Tisch in Wartung',
    'admin.dishName': 'Gerichtname',
    'admin.description': 'Beschreibung',
    'admin.price': 'Preis',
    'admin.category': 'Kategorie',
    'admin.addDish': 'Gericht hinzufügen',
    'admin.current': 'Aktuell',
    'admin.assignTable': 'Bàn zuweisen',
    'admin.customerInfo': 'Kundeninformationen',
    'admin.customerName': 'Kundenname',
    'admin.enterCustomerName': 'Kundenname eingeben',
    'admin.phoneNumber': 'Telefonnummer',
    'admin.email': 'E-Mail',
    'admin.numberOfGuests': 'Anzahl Gäste',
    'admin.tableStatus': 'Tischstatus',
    'admin.reservedDesc': 'Für später reserviert',
    'admin.occupiedDesc': 'Gäste sind anwesend',
    'admin.cancel': 'Abbrechen',
    'admin.close': 'Schließen',
    'admin.editCustomer': 'Kunde bearbeiten',
    'admin.noCustomerInfo': 'Keine Kundeninformationen',
    'admin.time': 'Zeit',
    'admin.guests': 'Gäste',
    'admin.status.available': 'Verfügbar',
    'admin.status.occupied': 'Besetzt',
    'admin.status.reserved': 'Reserviert',
    'admin.status.cleaning': 'Reinigung',
    'admin.reservationStatus.pending': 'Ausstehend',
    'admin.reservationStatus.confirmed': 'Bestätigt',
    'admin.reservationStatus.rejected': 'Abgelehnt',
    'admin.orderStatus.pending': 'Ausstehend',
    'admin.orderStatus.confirmed': 'Bestätigt',
    'admin.orderStatus.rejected': 'Abgelehnt',
    'admin.timeSlots': 'Zeitslots',
  },
  vi: {
    // Header
    'nav.home': 'Trang chủ',
    'nav.menu': 'Thực đơn',
    'nav.booking': 'Đặt bàn',
    'nav.about': 'Về chúng tôi',
    'nav.contact': 'Liên hệ',
    
    // Hero
    'hero.title': 'Nhà hàng Chang',
    'hero.subtitle': 'Trải nghiệm hương vị châu Á đích thực trong không gian thanh lịch. Nguyên liệu tươi ngon, công thức truyền thống và dịch vụ xuất sắc.',
    'hero.reserve': 'Đặt bàn',
    'hero.menu': 'Xem thực đơn',
    
    // Menu
    'menu.title': 'Thực đơn của chúng tôi',
    'menu.subtitle': 'Khám phá những món ăn được chế biến tỉ mỉ từ những nguyên liệu tốt nhất',
    'menu.recommendations': 'Món được đề xuất',
    'menu.ourRecommendations': 'BẾP CHÚNG TÔI ĐỀ XUẤT',
    'menu.appetizers': 'Khai vị',
    'menu.salads': 'Salad',
    'menu.mains': 'Món chính',
    'menu.desserts': 'Tráng miệng',
    'menu.beverages': 'Đồ uống',
    'menu.addToOrder': 'Thêm vào đơn',
    'menu.spicy': 'Cay',
    'menu.vegetarian': 'Chay',
    'menu.featured': 'Nổi bật',
    
    // Booking
    'booking.title': 'Đặt bàn tại Nhà hàng Chang Bistro',
    'booking.poweredBy': 'POWERED BY RESERV.ON',
    'booking.description': 'Ẩm thực Thái tinh tế và các món đặc sản quốc tế – được diễn giải hiện đại, phối hợp theo mùa và trình bày lễ hội. Dù bạn đến một mình để thưởng thức bữa tối thư giãn hay cùng bạn bè và gia đình để có một bữa tiệc cho các giác quan – chúng tôi chào đón bạn một cách nồng nhiệt. Chúng tôi mong được đón tiếp bạn và mang đến cho bạn một buổi tối khó quên.',
    'booking.date': 'Ngày',
    'booking.guests': 'Số người',
    'booking.times': 'Giờ có sẵn',
    'booking.selectDate': 'Vui lòng chọn ngày trước',
    'booking.moreThan10': 'Hơn 10 người?',
    'booking.email': 'E-Mail',
    'booking.call': 'Gọi điện',
    'booking.continue': 'TIẾP TỤC',
    'booking.contactInfo': 'Thông tin liên hệ',
    'booking.firstName': 'Tên',
    'booking.lastName': 'Họ',
    'booking.emailAddress': 'Địa chỉ email',
    'booking.phone': 'Số điện thoại',
    'booking.specialRequests': 'Yêu cầu đặc biệt',
    'booking.specialRequestsPlaceholder': 'Dị ứng, hạn chế chế độ ăn, dịp đặc biệt...',
    'booking.confirmReservation': 'XÁC NHẬN ĐẶT BÀN',
    'booking.back': 'QUAY LẠI',
    'booking.reservationSuccess': 'Đặt bàn thành công cho {guests} người vào ngày {date} lúc {time}.\n\nChúng tôi mong được chào đón bạn!',
    
    // About
    'about.title': 'Về Nhà hàng Chang',
    'about.subtitle': 'Hành trình ẩm thực qua châu Á với hương vị đích thực và cách trình bày hiện đại',
    'about.story': 'Câu chuyện của chúng tôi',
    'about.storyText1': 'Được thành lập vào năm 2015, Nhà hàng Chang đã tận tâm mang ẩm thực châu Á đích thực đến trung tâm thành phố. Các đầu bếp bậc thầy của chúng tôi kết hợp kỹ thuật nấu ăn truyền thống với nguyên liệu tươi ngon.',
    'about.storyText2': 'Chúng tôi tin rằng thức ăn không chỉ là dinh dưỡng – đó là cách để gắn kết mọi người, chia sẻ văn hóa và tạo ra những kỷ niệm lâu dài.',
    'about.awardWinning': 'Đoạt giải thưởng',
    'about.awardText': 'Được công nhận bởi các nhà phê bình ẩm thực địa phương và vinh danh với nhiều giải thưởng ẩm thực',
    'about.madeWithLove': 'Làm bằng tình yêu',
    'about.loveText': 'Mỗi món ăn được chuẩn bị với đam mê và sự chú ý đến từng chi tiết bởi các đầu bếp tài năng',
    'about.freshIngredients': 'Nguyên liệu tươi',
    'about.freshText': 'Chúng tôi tìm nguồn nguyên liệu tốt nhất hàng ngày để đảm bảo chất lượng và tính đích thực',
    
    // Contact
    'contact.title': 'Ghé thăm chúng tôi',
    'contact.subtitle': 'Tìm chúng tôi ở trung tâm thành phố, sẵn sàng phục vụ bạn ẩm thực đặc biệt',
    'contact.address': 'Địa chỉ',
    'contact.phone': 'Điện thoại',
    'contact.email': 'Email',
    'contact.hours': 'Giờ mở cửa',
    'contact.findUs': 'Tìm chúng tôi',
    'contact.mapComing': 'Bản đồ tương tác sắp ra mắt',
    
    // Cart
    'cart.title': 'Đơn hàng của bạn',
    'cart.empty': 'Giỏ hàng trống',
    'cart.emptySubtext': 'Thêm những món ngon từ thực đơn của chúng tôi',
    'cart.contactInfo': 'Thông tin liên hệ',
    'cart.addContactInfo': 'Thêm thông tin liên hệ',
    'cart.deliveryMethod': 'Phương thức giao hàng',
    'cart.selectDeliveryMethod': 'Chọn phương thức giao hàng',
    'cart.orderItems': 'Món đã đặt',
    'cart.subtotal': 'Tạm tính',
    'cart.tax': 'Thuế',
    'cart.total': 'Tổng cộng:',
    'cart.continue': 'Tiếp tục',
    'cart.back': 'Quay lại',
    'cart.fullName': 'Họ và tên',
    'cart.enterName': 'Nhập họ và tên của bạn',
    'cart.phone': 'Số điện thoại',
    'cart.email': 'Địa chỉ email',
    'cart.pickup': 'Đến lấy',
    'cart.delivery': 'Giao hàng',
    'cart.pickupTime': '15-25 phút',
    'cart.deliveryTime': '30-45 phút',
    'cart.deliveryAddress': 'Địa chỉ giao hàng',
    'cart.enterAddress': 'Nhập địa chỉ giao hàng',
    'cart.paymentMethod': 'Phương thức thanh toán',
    'cart.cash': 'Tiền mặt',
    'cart.card': 'Thẻ',
    'cart.payOnDelivery': 'Thanh toán khi giao/lấy hàng',
    'cart.payOnline': 'Thanh toán trực tuyến',
    'cart.specialNotes': 'Ghi chú đặc biệt',
    'cart.notesPlaceholder': 'Dị ứng, yêu cầu đặc biệt...',
    'cart.orderSummary': 'Tóm tắt đơn hàng',
    'cart.deliveryInfo': 'Thông tin giao hàng',
    'cart.contact': 'Liên hệ',
    'cart.method': 'Phương thức',
    'cart.address': 'Địa chỉ',
    'cart.payment': 'Thanh toán',
    'cart.placeOrder': 'Đặt hàng',
    'cart.termsNote': 'Bằng cách đặt hàng, bạn chấp nhận các điều khoản và điều kiện của chúng tôi',
    'cart.orderSuccess': 'Đặt hàng thành công!\n\nMón: {items}\nTổng: €{total}\nLiên hệ: {contact}\nPhương thức: {method}\n\nCảm ơn bạn đã đặt hàng!',
    
    // Footer
    'footer.description': 'Trải nghiệm ẩm thực châu Á đích thực trong không gian thanh lịch. Nguyên liệu tươi ngon, công thức truyền thống và dịch vụ xuất sắc.',
    'footer.quickLinks': 'Liên kết nhanh',
    'footer.contact': 'Liên hệ',
    'footer.rights': '© 2025 Nhà hàng Chang. Tất cả quyền được bảo lưu.',
    
    // Admin
    'admin.dashboard': 'Bảng điều khiển',
    'admin.overview': 'Tổng quan',
    'admin.reservations': 'Đặt bàn',
    'admin.orders': 'Đơn hàng',
    'admin.menuManagement': 'Quản lý thực đơn',
    'admin.backToWebsite': 'Về trang chính',
    'admin.selectTimeSlot': 'Chọn khung giờ',
    'admin.tableOverview': 'Sơ đồ bàn',
    'admin.table': 'Bàn',
    'admin.seats': 'chỗ ngồi',
    'admin.at': 'lúc',
    'admin.people': 'người',
    'admin.manageReservations': 'Quản lý đặt bàn',
    'admin.manageOrders': 'Quản lý đơn hàng',
    'admin.specialRequests': 'Yêu cầu đặc biệt',
    'admin.approve': 'Duyệt',
    'admin.reject': 'Từ chối',
    'admin.edit': 'Chỉnh sửa',
    'admin.orderedItems': 'Món đã đặt',
    'admin.deliveryAddress': 'Địa chỉ giao hàng',
    'admin.delivery': 'Giao hàng',
    'admin.pickup': 'Đến lấy',
    'admin.addNewDish': 'Thêm món mới',
    'admin.available': 'Có sẵn',
    'admin.unavailable': 'Không có sẵn',
    'admin.tableManagement': 'Quản lý bàn',
    'admin.addNewTable': 'Thêm bàn mới',
    'admin.editTable': 'Sửa bàn',
    'admin.addTable': 'Thêm bàn',
    'admin.updateTable': 'Cập nhật bàn',
    'admin.numberOfSeats': 'Số chỗ ngồi',
    'admin.location': 'Vị trí',
    'admin.enterLocation': 'Nhập vị trí bàn',
    'admin.active': 'Hoạt động',
    'admin.maintenance': 'Bảo trì',
    'admin.activeDesc': 'Bàn có thể sử dụng',
    'admin.maintenanceDesc': 'Bàn đang bảo trì',
    'admin.dishName': 'Tên món',
    'admin.description': 'Mô tả',
    'admin.price': 'Giá',
    'admin.category': 'Danh mục',
    'admin.addDish': 'Thêm món',
    'admin.current': 'Hiện tại',
    'admin.assignTable': 'Gán bàn',
    'admin.customerInfo': 'Thông tin khách hàng',
    'admin.customerName': 'Tên khách hàng',
    'admin.enterCustomerName': 'Nhập tên khách hàng',
    'admin.phoneNumber': 'Số điện thoại',
    'admin.email': 'Email',
    'admin.numberOfGuests': 'Số khách',
    'admin.tableStatus': 'Trạng thái bàn',
    'admin.reservedDesc': 'Đã đặt trước',
    'admin.occupiedDesc': 'Khách đang ngồi',
    'admin.cancel': 'Hủy',
    'admin.close': 'Đóng',
    'admin.editCustomer': 'Sửa thông tin khách',
    'admin.noCustomerInfo': 'Không có thông tin khách hàng',
    'admin.time': 'Giờ',
    'admin.guests': 'Khách',
    'admin.status.available': 'Có sẵn',
    'admin.status.occupied': 'Đang sử dụng',
    'admin.status.reserved': 'Đã đặt',
    'admin.status.cleaning': 'Đang dọn dẹp',
    'admin.reservationStatus.pending': 'Chờ duyệt',
    'admin.reservationStatus.confirmed': 'Đã xác nhận',
    'admin.reservationStatus.rejected': 'Đã từ chối',
    'admin.orderStatus.pending': 'Chờ duyệt',
    'admin.orderStatus.confirmed': 'Đã xác nhận',
    'admin.orderStatus.rejected': 'Đã từ chối',
    'admin.timeSlots': 'Khung giờ',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('de');

  const t = (key: string): string => {
    const translation = translations[language][key as keyof typeof translations[typeof language]];
    return translation || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}